[neofetch]
git-tree-sha1 = "cb1eaa1bde8fa5a2711b56cdf548ad6d8512a216"

    [[neofetch.download]]
    sha256 = "e9ab24f95a0827141aa9c47d871a9c63a5fbcf37d4a99d1b62197f5c99fd77c1"
    url = "https://github.com/JuliaBinaryWrappers/neofetch_jll.jl/releases/download/neofetch-v7.1.0+0/neofetch.v7.1.0.any.tar.gz"
