# Autogenerated wrapper script for neofetch_jll for any
export neofetch

JLLWrappers.@generate_wrapper_header("neofetch")
JLLWrappers.@declare_file_product(neofetch)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        neofetch,
        "bin/neofetch",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
